# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            Datalearner
tagline:          Programming stats in Python and R
url:              http://clarkfitzg.github.io
paginate:         1
baseurl:          /
author:
  name:           Clark Fitzgerald
  url:            https://twitter.com/clarkfitzg
  email:          clarkfitzg@gmail.com

# Custom vars
version:          1.0.0
github:
  repo:           https://github.com/clarkfitzg/clarkfitzg.github.io

pages_list:       
  About: '/about'
  Archive: '/archive'
